version: '3.8'

services:
  api:
    build: ./api
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:pg_password@postgres_db:5432/screenshot_db
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    depends_on:
      - db
      - minio
      - selenium

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: screenshot_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"